name: Keep Space Alive
on:
  schedule:
    - cron: '*/5 * * * *' # প্রতি ৫ মিনিট পরপর ট্রিগার হবে
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Space Loop
        run: |
          # ৫ মিনিটের (৩০০ সেকেন্ড) মধ্যে ৩০ সেকেন্ড পরপর ১০ বার পিং করবে
          for i in {1..10}
          do
            curl -s https://0xhexz-hex.hf.space > /dev/null
            echo "Ping $i successful..."
            sleep 30
          done
